# Generated by Django 5.1.4 on 2024-12-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresult_quiz_quizre_timesta_0b1971_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
